//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleado.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Empleados
    {
        public int Clave_Emp { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public System.DateTime FecNac { get; set; }
        public int Departamento { get; set; }
        public decimal sueldo { get; set; }

        [NotMapped]
    public List<Departamentos> EmpleadosDepartamentos { set; get; }
    

        
         
    }
    
}
